### PR TITLE
Add GH action to publish frontend to GH pages

### PR DESCRIPTION
**Pull request by sebastiantoh**
Rationale:

I think it's best if certain features are tested on an actual mobile device such as GPS, adding attachments (e.g. file picker / gallery), camera(?), etc. 

GH pages is useful as a temporary measure to support viewing the app on our mobile devices

PS: haven't actually tested this PR

### CODE REVIEW

**Comment by ianyong** [comment]
> PS: haven't actually tested this PR

Could you temporarily edit the Github Actions config to run on this branch too as a sanity check? We can revert the commit once we verify that it works.

**Comment by sebastiantoh** [comment]
> > PS: haven't actually tested this PR
> 
> Could you temporarily edit the Github Actions config to run on this branch too as a sanity check? We can revert the commit once we verify that it works.

Sure, turns out there were quite a lot of issues haha :x But should be mostly fixed.

Some non-ideal things to note:
- using `dotenv` instead of `.env`
- no Google Map API key is supplied since this will be mostly used just for testing

If all is good, I'll remove the temp commit!

https://hansel-app.github.io/hansel/#/

**Comment by ianyong** [comment]
> > > PS: haven't actually tested this PR
> > 
> > 
> > Could you temporarily edit the Github Actions config to run on this branch too as a sanity check? We can revert the commit once we verify that it works.
> 
> Sure, turns out there were quite a lot of issues haha :x But should be mostly fixed.
> 
> Some non-ideal things to note:
> 
> * using `dotenv` instead of `.env`
> * no Google Map API key is supplied since this will be mostly used just for testing
> 
> If all is good, I'll remove the temp commit!
> 
> https://hansel-app.github.io/hansel/#/

Looks good! One thing though, can the `gh-pages` branch be orphaned rather than branching off `master`?

**Review by ianyong — DISMISSED** [review]
LGTM! Can merge once the temp commit is reverted. Thanks!

**Pull request merged**
