### PR TITLE
[Draft] Carousels

### PR DESCRIPTION
**Pull request by okg00dbye**
Save me from css ahhhh

### CODE REVIEW

**Comment by sebastiantoh** [comment]
Don't have to change your implementation, but just checking, does https://youzan.github.io/vant/#/en-US/swipe work as a carousel?

**Comment by okg00dbye** [comment]
> Don't have to change your implementation, but just checking, does https://youzan.github.io/vant/#/en-US/swipe work as a carousel?

Ah that was my initial attempt, tried tweaking around with it for quite a while but my CSS not strong enough haha ;-; maybe an advantage with this package is also seems easier to set the styles for the neighboring slides (like the suggested friends carousel in figma) and slide transitions also

Also open call for help haha: abit stumped on how to center the selected color of gemColorCarousel to be the center of the screen, if anyone has CSS ideas please feel free to commit~

**Comment by sebastiantoh** [comment]
> Ah that was my initial attempt, tried tweaking around with it for quite a while but my CSS not strong enough haha ;-; maybe an advantage with this package is also seems easier to set the styles for the neighboring slides (like the suggested friends carousel in figma) and slide transitions also

I see!

> Also open call for help haha: abit stumped on how to center the selected color of gemColorCarousel to be the center of the screen, if anyone has CSS ideas please feel free to commit~

Do you want to try a different library?

1) https://swiperjs.com/vue
  - This is a generic JS library
  - https://swiperjs.com/demos#centered

2) https://github.com/surmon-china/vue-awesome-swiper
  - Based off the above library as well
  - Has centered slides as well (Search 'Centered slides' on https://github.surmon.me/vue-awesome-swiper/)

**Comment by okg00dbye** [comment]
> Do you want to try a different library?
> 
> 1. https://swiperjs.com/vue
> 
> * This is a generic JS library
> * https://swiperjs.com/demos#centered
> 
> 1. https://github.com/surmon-china/vue-awesome-swiper
> 
> * Based off the above library as well
> * Has centered slides as well (Search 'Centered slides' on https://github.surmon.me/vue-awesome-swiper/)

Thanks! Tried vue-awesome-swiper before, wasn't compatible with vue3, will see if Swiper helps

**Comment by okg00dbye** [comment]
Assuming I can close this

**Pull request closed without merging**
