### PR TITLE
Update GH action for publishing to GH pages 

### PR DESCRIPTION
**Pull request by sebastiantoh**
Will revert  temp commit 1677f4c once this is approved!

https://hansel-app.github.io/hansel/

### CODE REVIEW

**Comment by ianyong** [comment]
Getting the following error on the page:
> This page can't load Google Maps correctly.

**Comment by sebastiantoh** [comment]
oh, I think that's cos I didn't supply an API key. I think the site works fine if you dismiss that error

**Comment by ianyong** [comment]
> oh, I think that's cos I didn't supply an API key. I think the site works fine if you dismiss that error

Ah okay, I guess this isn't a top priority since we'll be adding our own Docker setup later.

**Review by ianyong — DISMISSED** [review]
LGTM! Can revert the temp commit, thanks!

**Pull request merged**
