### PR TITLE
add gem carousel 

### PR DESCRIPTION
**Pull request by sebastiantoh**

### CODE REVIEW

**Review by okg00dbye — APPROVED** [review]
lgtm tq

**Comment by ming-00** [comment]
Nicee it looks really great :-) Just checking, is the gem image supposed to load?

**Comment by sebastiantoh** [comment]
> Nicee it looks really great :-) Just checking, is the gem image supposed to load?

not yet, working on it!

**Comment by ming-00** [comment]
> not yet, working on it!

Okay! If you have anything else you need to work on I can take over lmk~

**Pull request merged**
