### PR TITLE
Update UI for Map

### PR DESCRIPTION
**Pull request by sebastiantoh**
Branched off https://github.com/hansel-app/hansel/pull/33

a

Thoughts?

### CODE REVIEW

**Comment by ming-00** [comment]
> Branched off #33
> 
> a
> 
> Thoughts?

Ooh such a good idea to include number of gems and closest distance! I think it takes up quite a bit of space on the screen though, and it's a "read once" kind of information, wdyt of an info icon below the go to my location icon, and when clicked there will be a pop up which can be closed? Lemme try to add that on figma rn~

Sorry for the delay, we also tweaked the map ui a bit on figma just now 😅 It's pretty close to your design, what do you think?

**Comment by sebastiantoh** [comment]
Yep, agree with your thoughts! I think the Figma stuff looks good as well. But I have some concerns about having the drop gem button being situated between the arrows. Doesnt really feel like it fits? Cos it sort of does different things (one is manipulating the current mapwhile the other is manipulating another person's map by adding a gem)


Also, how do you envision a user will pick up a gem? By tapping on the gem in the map?

**Comment by ming-00** [comment]
> Yep, agree with your thoughts! I think the Figma stuff looks good as well. But I have some concerns about having the drop gem button being situated between the arrows. Doesnt really feel like it fits? Cos it sort of does different things (one is manipulating the current mapwhile the other is manipulating another person's map by adding a gem)

Yeah I agree too :/ Lemme sleep on it... 

> Also, how do you envision a user will pick up a gem? By tapping on the gem in the map?

I think when user is close enough when the tooltip could automatically open, and at the bottom of the tooltip there can be a "pick up gem" button? Or does google maps offer some animations like radiating markers or sth :')

**Comment by sebastiantoh** [comment]
> I think when user is close enough when the tooltip could automatically open, and at the bottom of the tooltip there can be a "pick up gem" button? Or does google maps offer some animations like radiating markers or sth :')

Sure, sounds good! Unfortunately I dont think google maps has animations :cry:

**Comment by ming-00** [comment]
> Sure, sounds good! Unfortunately I dont think google maps has animations 😢

Ay I was also thinking, wdyt if the user has a radius around their location so it's easier to see which gems are in range?

**Comment by ming-00** [comment]
What if... instead of the arrows to cycle through gems being below, they appear with tooltip? I think it won't be too inconvenient for users since when cycling the gems are centred against the map 

Screenshot 2021-09-20 at 12 18 41 PM

Upon first opening the map, or clicking i:
Screenshot 2021-09-20 at 12 19 13 PM
oops tooltip meant to be white here^

**Comment by sebastiantoh** [comment]
> What if... instead of the arrows to cycle through gems being below, they appear with tooltip? I think it won't be too inconvenient for users since when cycling the gems are centred against the map
> 
> Screenshot 2021-09-20 at 12 18 41 PM
> 
> Upon first opening the map, or clicking i:
> Screenshot 2021-09-20 at 12 19 13 PM
> oops tooltip meant to be white here^

thanks, looks good! I'll try to make it based on the images here!

**Comment by sebastiantoh** [comment]
i tried adding the buttons to the tooltip, but i couldn't get it to work :'(

Left it at the bottom for now

TODOs:
- Wrap drop gem text in circular fashion
- Try placing left/right buttons back to tooltip

**Review by ianyong — APPROVED** [review]
LGTM!

**Pull request merged**
