### PR TITLE
Splash screen + implementing native look and feel

### PR DESCRIPTION
**Pull request by ming-00**
Sorry for bloated PR... ended up sidetracked and wrestling CSS 😠 

Aka milestones 7 & 12
 - Added route between login & register page
 - Fixed bug where buttons align vertically w/ long names, but long names still an issue
 - Added swipe features for hamburger menu and bottom sheet + back swipe features for backable pages
 - Adding splash screen image... but I can't test or find where to put it
 - Finished pickup gem pages + integrated to take gem
 - Fix flash of unstyled content issue

 - Terrible route transitions progress: for some reason it only works on the pickup gem page, if I missed anything please let me know :0

### CODE REVIEW

**Comment by sebastiantoh** [comment]
Actually, what are all the android-chrome-maskable-192x192.png and stuff used for?

**Comment by ming-00** [comment]
> Actually, what are all the android-chrome-maskable-192x192.png and stuff used for?

It's just standard favicon assets!
https://openbase.com/js/vue-pwa-asset-generator/documentation

**Comment by sebastiantoh** [comment]
> > Actually, what are all the android-chrome-maskable-192x192.png and stuff used for?
> 
> It's just standard favicon assets!
> https://openbase.com/js/vue-pwa-asset-generator/documentation

i see! is it supposed to be the vue icon though?

**Comment by ming-00** [comment]
> i see! is it supposed to be the vue icon though?

Omg I think it got overwritten when I merged master or it got auto generated 😭 Thanks for pointing out

**Review by sebastiantoh — APPROVED** [review]
lgtm!

**Pull request merged**
