### PR TITLE
Displaying base64 avatars + placeholders

### PR DESCRIPTION
**Pull request by okg00dbye**
image

FriendCell/HamburgerMenu/ProfilePages takes in base64String instead of placeholderAvatarUrl now to display user avatar
Used '1' to '5' to map to one of our five default avatars (thinking this is in case they want to choose another default avatar and we need to store their choice as well)
TODO: set avatar in EditProfile

!! @ming-00 
a lot of pages might display empty for you after this PR is merged as I changed them to read from store instead of mockData. Can add these inside HomePage.vue to continue being able to test
image

### CODE REVIEW

**Comment by sebastiantoh** [comment]
ps can help to display the avatar in the gem map tooltip as well? 
image

**Comment by okg00dbye** [comment]
> ps can help to display the avatar in the gem map tooltip as well?
> image

Can't verify the exact value, I'm assuming Bobby Bob's will be empty string because he doesn't have an avatar in the seed. Accounted for empty string - they will become GIRL1
image

**Review by sebastiantoh — APPROVED** [review]
lgtm!

**Comment by sebastiantoh** [comment]
ps, I accidentally pushed a commit which doesn't work. I'll fix it in my other PR

**Pull request merged**
