### PR TITLE
Fix search bars losing text when focus is lost

### LINKED ISSUE #93: Search bars lose their text when focus is lost

### PR DESCRIPTION
**Pull request by ianyong**
Fixes #93.

### CODE REVIEW

**Comment by ming-00** [comment]
also the drop gem page!

**Comment by ianyong** [comment]
> also the drop gem page!

Ah yea, that's `frontend/src/pages/DropGem/SelectFriend.vue` right?

**Comment by ming-00** [comment]
> Ah yea, that's `frontend/src/pages/DropGem/SelectFriend.vue` right?

Also AttachMessage.vue under drop gem!

**Comment by okg00dbye** [comment]
> > Ah yea, that's `frontend/src/pages/DropGem/SelectFriend.vue` right?
> 
> Also AttachMessage.vue under drop gem!

AttachMessage.vue should be fixed with #108

**Review by sebastiantoh — DISMISSED** [review]
lgtm!

**Comment by ianyong** [comment]
> lgtm!

I've resolved the merge conflicts!

**Review by sebastiantoh — APPROVED** [review]

**Pull request merged**
