### PR TITLE
Add tooltip window when tapping on gem markers

### PR DESCRIPTION
**Pull request by sebastiantoh**
Other changes:
- changed the middle button to route to the drop gem page (not sure if this is alright)
- Created separate Home page

TODOs in another PR:
- styling and UI lol
- route to pick up gem page when within certain threshold radius
- add menu (are we still doing this?)

### CODE REVIEW

**Comment by ming-00** [comment]
Looking good! :-) 💃🏻 💃🏻 💃🏻 

Some feature suggestions:
 - Clicking elsewhere should close the tooltip?
 - I'm wondering if the zoom out can be a bit more, enough so that it's not too difficult to pan around sg at least
 - If I'm reading the code correctly, is it distance will always be showed in km? Even if it is v near

Hmm I'm not sure what you think about the menu! Bc if we are not doing chat and only have a gem history, then it can be stashed under profile? In that case there will only be two main pages: map + profile. What are your thoughts :0

**Comment by ming-00** [comment]
Also one more general thing, are all our pages gonna fill out the width on desktop... bc for pick up gem, the pic is gonna have mobile dimensions, not sure how it should look then

**Comment by sebastiantoh** [comment]
>     * Clicking elsewhere should close the tooltip?

Sounds good! I've made it such that tapping (only taps) elsewhere closes the tooltip. I've also made it such that only 1 tooltip can be open at any one time.

>     * I'm wondering if the zoom out can be a bit more, enough so that it's not too difficult to pan around sg at least

Sure!

>     * If I'm reading the code correctly, is it distance will always be showed in km? Even if it is v near

I've modified it to display distances in metres if it's less than a km.

> Hmm I'm not sure what you think about the menu! Bc if we are not doing chat and only have a gem history, then it can be stashed under profile? In that case there will only be two main pages: map + profile. What are your thoughts :0

Sounds good!

**Comment by sebastiantoh** [comment]
> Also one more general thing, are all our pages gonna fill out the width on desktop... bc for pick up gem, the pic is gonna have mobile dimensions, not sure how it should look then

hmm, I think it doesn't matter. We probably don't have to fill out the width for the other pages + they don't care how it looks on desktop haha

**Comment by ming-00** [comment]
> hmm, I think it doesn't matter. We probably don't have to fill out the width for the other pages + they don't care how it looks on desktop haha

That's true! okok

One last thing, do you think when cycling through the gems, the tooltip for that gem should automatically open?

**Comment by sebastiantoh** [comment]
> > hmm, I think it doesn't matter. We probably don't have to fill out the width for the other pages + they don't care how it looks on desktop haha
> 
> That's true! okok
> 
> One last thing, do you think when cycling through the gems, the tooltip for that gem should automatically open?

Yes, good idea! Implemented!

**Review by ming-00 — APPROVED** [review]
Niceee lgtm!

**Pull request merged**
